### ISSUE TITLE
Update folders or imports in quick start example

### ISSUE THREAD

**Issue by kevinrobinson** [google/ml-fairness-gym#1]
hello, thanks for sharing! 👍 

The quick start doesn't work for me:
```
Traceback (most recent call last):
  File "examples/lending_demo.py", line 26, in <module>
    from agents import threshold_policies
ModuleNotFoundError: No module named 'agents'
```

I think this is trying to import a file, but `agents/threshold_policies` is in the root and not the `examples` folder.

This works though:
```
$ cp examples/lending_demo.py .
$ python ./lending_demo.py --num_steps=500
```
...and opens a bunch of windows with charts! :)

So maybe these paths or imports need to be updated, or the quick start instructions?  I'm using `conda` so if this is just because of that vs. virtualenv then sorry if I don't know enough to tell the difference, just trying to be helpful :)

**Comment by hansa0** [comment]
Hi - thanks for trying out the ml-fairness-gym demo!

Our current solution for the problem you are describing is to add the ml-fairness-gym directory to your PYTHONPATH as described in the [installation instructions](https://github.com/google/ml-fairness-gym/blob/master/docs/installation.md). 

We plan on restructuring the folders and files in the repo so that this doesn't happen in our next version.
